version: '3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/project
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  php:
    build: .
    environment:
      DATABASE_URL: "mysql://root:toor@database:3306/database?serverVersion=8&charset=utf8mb4"
    volumes:
      - ./:/var/www/project
    depends_on:
      - database

  database:
    image: mysql:8.0
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: database
    volumes:
      - ./sqlData:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
